### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by drew1two** [luyadev/luya-deployer#14]
Found another Basil :(  Must be me :)

### What steps will reproduce the problem?
composer require luyadev/luya-deployer --dev

### What is the expected result?
install luya-deployer

### What do you get instead? (A Screenshot can help us a lot!)

    - Can only install one of: symfony/process[v3.4.9, v4.4.2].
    - Installation request for symfony/process (locked at v4.4.2) -> satisfiable by symfony/process[v4.4.2].

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))
I removed the mod_rewrite check as it was erroring cause I use nginx php-fpm.
The rest are:-

 1: [ini_get('short_open_tag')] ''<br /> 2: [ini_get('error_reporting')] '22527'<br /> 3: [phpversion()] '7.2.26'<br /> 4: [php_ini_loaded_file()] '/etc/php.ini'<br /> 5: [php_sapi_name()] 'cli'<br />PHP Warning:  Use of undefined constant unknown - assumed 'unknown' (this will throw an Error in a future version of PHP) in /web/luya-kickstarter/public_html/luyacheck.php(22) : eval()'d code on line 1

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | luya-core = 1.0, luya-module-cms = 2.0
| PHP Version      | 7.2
| Platform         | LEMP
| Operating system | Centos 6.4

**Comment by drew1two** [comment]
Looks like I've got a composer version conflict... looking into it

**Comment by drew1two** [comment]
Found this from deployer creator:-

deployed.org is online. And yes I was in rush for Symfony 5 and introduced BC. I’m gonna fix it be releasing v7 with Symfony 5 only return compatibility with PHP 7.0. Or you can fix version of deployer in composer.json.  What do you think?


Can we take his advice try use 6.7.2 version instead?

**Comment by nadar** [comment]
make sure you don't us minimum-stability: dev in your composer.json

please past your composer.json here, so we are able to reproduce and help, otherwise not

**Comment by drew1two** [comment]
using 
composer require luyadev/luya-deployer --dev
gives the above error. 

{
    "name": "luyadev/luya-kickstarter",
    "description": "The kickstarter project for a new LUYA application.",
    "type": "luya-kickstarter",
    "license":"MIT",
    "require": {
        "luyadev/luya-core" : "^1.0",
        "luyadev/luya-module-admin" : "^2.0",
        "luyadev/luya-module-cms" : "^2.0",
        "luyadev/luya-bootstrap3" : "^1.0",
        "luyadev/luya-generic" : "^2.0"
    },
    "require-dev": {
        "yiisoft/yii2-gii" : "^2.0",
        "yiisoft/yii2-debug" : "^2.0",
        "luyadev/luya-testsuite" : "^1.0"
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "public_html/assets": "0777",
                    "public_html/storage": "0777",
                    "runtime" : "0777"
                }
            ]
        },
        "asset-installer-paths": {
            "bower-asset-library": "vendor/bower"
        },
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        }
    },
    "config": {
        "fxp-asset": {
            "enabled": false
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}

**Comment by nadar** [comment]
1. make sure composer is latest `composer self-update`
2. try to add the deployer to your composer.json like `luyadev/luya-deployer":"^1.0"` and run composer update

**Comment by drew1two** [comment]
You are already using composer version 1.9.2 (stable channel).

putting it in composer.json directly now

**Comment by nadar** [comment]
I also removed the composer.lock file and released 1.0.8.1 - this might help as well

**Comment by drew1two** [comment]
luyadev/luya-deployer":"^1.0" worked :)
It 'Downgrading symfony/process (v4.4.2 => v3.4.36)' :)


composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 39 installs, 1 update, 0 removals
  - Installing symfony/polyfill-mbstring (v1.13.1): Downloading (100%)
  - Installing psr/log (1.1.2): Downloading (100%)
  - Installing symfony/debug (v3.4.36): Downloading (100%)
  - Installing symfony/console (v3.4.36): Downloading (100%)
  - Installing herrera-io/version (1.1.1): Downloading (100%)
  - Installing seld/jsonlint (1.7.2): Downloading (100%)
  - Installing justinrainbow/json-schema (1.6.1): Downloading (100%)
  - Installing herrera-io/json (1.0.3): Downloading (100%)
  - Installing herrera-io/phar-update (2.0.0): Downloading (100%)
  - Installing deployer/phar-update (v1.0.0): Downloading (100%)
  - Installing phpseclib/phpseclib (2.0.23): Downloading (100%)
  - Downgrading symfony/process (v4.4.2 => v3.4.36): Downloading (100%)
  - Installing symfony/yaml (v3.4.36): Downloading (100%)
  - Installing symfony/finder (v3.4.36): Downloading (100%)
  - Installing symfony/var-exporter (v5.0.2): Downloading (100%)
  - Installing psr/container (1.0.0): Downloading (100%)
  - Installing symfony/service-contracts (v2.0.1): Downloading (100%)
  - Installing symfony/cache-contracts (v2.0.1): Downloading (100%)
  - Installing symfony/cache (v4.4.2): Downloading (100%)
  - Installing symfony/expression-language (v3.4.36): Downloading (100%)
  - Installing evenement/evenement (v2.1.0): Downloading (100%)
  - Installing react/stream (v0.4.6): Downloading (100%)
  - Installing react/promise (v2.7.1): Downloading (100%)
  - Installing react/event-loop (v0.4.3): Downloading (100%)
  - Installing react/socket (v0.4.6): Downloading (100%)
  - Installing react/promise-timer (v1.5.1): Downloading (100%)
  - Installing react/cache (v0.4.2): Downloading (100%)
  - Installing react/dns (v0.4.17): Downloading (100%)
  - Installing react/socket-client (v0.4.6): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing ringcentral/psr7 (1.2.2): Downloading (100%)
  - Installing react/http (v0.4.4): Downloading (100%)
  - Installing ralouphie/getallheaders (3.0.3): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.6.1): Downloading (100%)
  - Installing react/http-client (v0.4.17): Downloading (100%)
  - Installing react/child-process (v0.4.3): Downloading (100%)
  - Installing react/react (v0.4.2): Downloading (100%)
  - Installing elfet/pure (v2.0.0): Downloading (100%)
  - Installing deployer/deployer (v3.3.0): Downloading (100%)
  - Installing luyadev/luya-deployer (1.0.8): Downloading (100%)
symfony/console suggests installing symfony/event-dispatcher
symfony/console suggests installing symfony/lock
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
symfony/service-contracts suggests installing symfony/service-implementation
react/event-loop suggests installing ext-libevent (>=0.1.0)
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
react/react suggests installing ext-libevent (Allows for use of a more performant event-loop implementation.)
react/react suggests installing ext-libev (Allows for use of a more performant event-loop implementation.)
react/react suggests installing ext-event (Allows for use of a more performant event-loop implementation.)
deployer/deployer suggests installing herzult/php-ssh (For SSH support through native SSH2 extension)
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Package herrera-io/version is abandoned, you should avoid using it. No replacement was suggested.
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
Package react/socket-client is abandoned, you should avoid using it. Use react/socket instead.
Writing lock file
Generating autoload files

**Comment by drew1two** [comment]
Is symphony/process running at 3.4 instead of 4.4 going to cause you problems with luya?
