### ISSUE TITLE
config file being reset

### ISSUE THREAD

**Issue by drew1two** [luyadev/luya-deployer#15]
### What steps will reproduce the problem?
Have entered database config vars for ENV_PROD. 

run: ./vendor/bin/dep luya prod

receive: 
â¤ Executing task deploy:prepare
â¤ Executing task deploy:release
â¤ Executing task deploy:update_code
â¤ Executing task deploy:vendors
â¤ Executing task deploy:luya

In PhpSecLib.php line 124:

  Error: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)

check upstream... config.php has been reset to clean.  ie: has no settings entered.

### What is the expected result?
Not to receive the following error:-
Error: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

Can't run... Use nginx

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  latest
| PHP Version      | 7.2
| Platform         | LEMP
| Operating system | Centos 7.7

**Comment by nadar** [comment]
could you please provide config.php and deploy.php without sensitive data? Because the ENV_* will be set by what is defined in the deploy.php trough `  ->stage('prod')`

**Comment by drew1two** [comment]
I'm thinking the problem lies with the values I've used in "set('repository'"

I commented out the "set(repository" line in deploy.php because I didn't 'have' a repository.  But when I did I got the following error:-
Object `repository` does not exist in Collection.

So I left it in and entered my own git login details and blundered my way through the following errors:-
remote: Invalid username or password.
  fatal: Authentication failed for 'https://USER:PASSWORD@github.com/VENDOR/REPO.git/'

remote: Repository not found.
  fatal: repository 'https://{MYUSERNAME:MYPASSWORD}@github.com/VENDOR/REPO.git/' not found

Finally ended up with the following as the 'set repository' string
set('repository', 'https://{MYUSERNAME:MYPASSWORD}@github.com/luyadev/luya-kickstarter.git');

So I guess what's happening here is that it's pulling an instance of luya-kickstarter from that repository and that is overwriting my config.php file?

The documentation for deployer makes no mention of the values to enter in the 'set repository' string.

**Comment by nadar** [comment]
the concept of deployer is to deploy a git repository, so you have to provide a repository to deploy :-)

**Comment by drew1two** [comment]
Hehe  Shame we can't just 'deploy' our local instance to env_prod .... you're 'making' me have to use Best Practices here Basil lol

**Comment by drew1two** [comment]
Now I'll go learn how to create... push... commit to git

**Comment by nadar** [comment]
😄 it's really easy, you will see. You can create private repos for free on git and there are thounds of tutorials and videos. hope you achieved what you want. 👍 going to close the issue.

**Comment by drew1two** [comment]
Hi Basil... I still think this is an issue.. as in:-
I don't think production information should be kept on github to get this to work...
It should be reading from the deploy.php held locally to make the database connection.  
I have a master version on github now and everything goes well till that error again.  And I don't feel comfortable placing that information in a github repository no matter it is private :)
If it has to be in the repository... then why do we put it in the deploy.php?
In anycase... I do think you've made it to read from the deploy.php... but currently... it's not doing that.

**Comment by nadar** [comment]
So i think you are talking about the password for ssh connection, you can also use pem files or any other. The latest version of php deployer do not support password storage anymore. So maybe try this:

https://github.com/luyadev/luya-deployer/tree/add-idea-for-latest-deployer-version

But GIT is required anyhow

**Comment by drew1two** [comment]
Nope... I'm talking about ...
 Error: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)

**Comment by nadar** [comment]
https://github.com/luyadev/luya-kickstarter/blob/master/configs/config.php#L94-L100

**Comment by nadar** [comment]
you could try to use ENV variables in your php process or something like this ;-) but the db information must be stored somewhere.

**Comment by drew1two** [comment]
Why do we have to put the db information into deploy.php if it doesn't read from there?

**Comment by drew1two** [comment]
Sorry, I was mistaken...

**Comment by drew1two** [comment]
But couldn't we add to the deploy.php for database connection info instead of leaving it on a third party website?

**Comment by nadar** [comment]
database connection must be stored in the LUYA config. Sorry, maybe i don't understand what you are looking for. What do you mean by third party website?

**Comment by drew1two** [comment]
I mean github being the 3rd party website

**Comment by drew1two** [comment]
You pass that info to deployer though yes?

**Comment by nadar** [comment]
Just to be clear:

GIT (whether github, gitlab, bitbucket or if you are consernd about security, create your own git server -its open source)

Deployer: Just makes the connection between your computer and the webserver which runs the website.

LUYA Config: The place you CAN put all your informations.

You could also use env variables http://php.net/getenv and store db connection somewhere as env variable on the webserver.

**Comment by drew1two** [comment]
By you... I mean you've created it to use a file we create called 'deploy.php' .. that when executed by ... 'luya'.... passes the info to the deployer vendor.

**Comment by nadar** [comment]
luya deployer is just the PHP deployer (https://deployer.org/) project with some extra LUYA sugar on it. (https://github.com/luyadev/luya-deployer/blob/master/luya.php#L3)

**Comment by drew1two** [comment]
I was suggesting that when executing 'luya' it trap 'extra' info like production database connection details and pass 'that' onto deployer?
Haha  Yes.. Sugar... just needs one more teaspoon full of sugar and all would be Hunky Dory :)

**Comment by drew1two** [comment]
Anyways... I can kill my prod server should anything go awry :) Only using for testing... but now maybe... just maybe... what I'm asking could be put down as a 'feature request'? :)

**Comment by drew1two** [comment]
Still... love your work Basil :)

**Comment by nadar** [comment]
so you want to ENTER the connection for database while deploying, because of you don't want to store the database connection in git.

If this is the case, it would say this could be an option, but maybe it makes no sense to implement. Then better define those informations directly on your webserver with environment variables (like for example name `DB_CONFIG_DSN`) and add getenv('DB_CONFIG_DSN') in your config, otherwise you would have to enter those informations every time you deploy. Unless connection is only allowed from localhost, its anyhow not possible to connect to the sql server ;-) just saying.
