### ISSUE TITLE
beforeCommands executed after migration

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-deployer#4]
The beforeCommands will be executed after the migration. I prefer the beforeCommands would run as first.
In my special case I want make a simple backup, before start the deployment.

https://github.com/luyadev/luya-deployer/blob/b3cc82135f71b10e274189d7e14e5a8ebc03112a/luya.php#L34

**Comment by nadar** [comment]
I just pushed a commit with a new option `beforeCoreCommands` and a readme info:

Command execution lifecycle:

1. run beforeCoreCommands.
2. if adminCoreCommands is enabled: migration
3. run beforeCommands
4. if adminCoreCommands is enabled: import, health
5. run afterCommands

**Comment by nadar** [comment]
@boehsermoe and i have released version 1.0.3 of luya deployer, so you can use this command by adding ~1.0.0 constraint and run composer update

**Comment by boehsermoe** [comment]
Merci 👍
