### ISSUE TITLE
Extend Deploy Docs

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya-deployer#5]
- Adding docs how to deploy with git authtoken
- some general hints for private repo deployment

**Comment by nadar** [comment]
Private repo deployment is described in the docs.

**Comment by dev7ch** [comment]
more less i would say.

its onyl described with username and password. I think a detailed describtion how to use a identityfile and delpoy tokens would be helpful, at least a link where it is described.

What do you think?

**Comment by nadar** [comment]
i don't think there is more explanation required. But you can create a PR with a new file inside the docs folder for further explanations => https://github.com/luyadev/luya-deployer/tree/master/docs

I don't wont to bloat the readme.md even more.

**Comment by dev7ch** [comment]
yes good point, if i ll come to this "issue" again i ll add a new doc file (within the next weeks probably)

**Comment by dev7ch** [comment]
the deployer docs a pretty well, https://deployer.org/docs
